version: "3"

env:
  IMG_NS: securecodebox

tasks:
  prepare-testing-env:
    env:
      IMG_TAG:
        sh: 'echo "sha-$(git rev-parse --short HEAD)"'
    cmds:
      - 'echo "Deleting existing kind cluster for testing environment"'
      - kind delete cluster --name testing-env || true
      - 'echo "Starting kind cluster for testing environment"'
      - kind create cluster --name testing-env
      - 'echo "Building images for operator and lurker with tag ${IMG_TAG}"'
      - cd operator/ && docker build -t ${IMG_NS}/operator:${IMG_TAG} .
      - cd lurker/ && docker build -t ${IMG_NS}/lurker:${IMG_TAG} .
      - kind load docker-image ${IMG_NS}/operator:${IMG_TAG} --name testing-env
      - kind load docker-image ${IMG_NS}/lurker:${IMG_TAG} --name testing-env
      - 'echo "Deploying secureCodeBox operator to the testing environment"'
      - kubectl config use-context kind-testing-env
      - kubectl create namespace integration-tests || true
      - kubectl create namespace securecodebox-system || true
      - |
        helm -n securecodebox-system upgrade --install securecodebox-operator ./operator --wait \
          --set="image.repository=docker.io/${IMG_NS}/operator" \
          --set="image.tag=${IMG_TAG}" \
          --set="image.pullPolicy=IfNotPresent" \
          --set="lurker.image.repository=docker.io/${IMG_NS}/lurker" \
          --set="lurker.image.tag=${IMG_TAG}" \
          --set="lurker.image.pullPolicy=IfNotPresent"
      - |
        echo "Building parser-sdk images with tag ${IMG_TAG}"
        docker build -t securecodebox/parser-sdk-nodejs:${IMG_TAG} ./parser-sdk/nodejs
      - |
        echo "Building hook-sdk images with tag ${IMG_TAG}"
        docker build -t securecodebox/hook-sdk-nodejs:${IMG_TAG} ./hook-sdk/nodejs
