# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: "ffuf-config"
data:
  wordlist.txt: |
    blog
    404
    exampleHopefullyNotFound
---
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "ffuf-securecodebox.io"
spec:
  scanType: "ffuf"
  parameters:
    # the target
    - "-u"
    - https://www.securecodebox.io/FUZZ
    # wordlist
    - "-w"
    - /config/wordlist.txt
  volumes:
    - name: "ffuf-config"
      configMap:
        name: "ffuf-config"
  volumeMounts:
    - name: "ffuf-config"
      mountPath: "/config/"
