version: "3"

includes:
  scanner:
    taskfile: ../Taskfile.yaml
    flatten: true
    excludes:
      - predeploy
    vars:
      scannerName: nuclei
      additionalHelmInstallArgsForScanner: |
        --set="scanner.image.pullPolicy=IfNotPresent" \
        --set="nucleiTemplateCache.enabled=false" \

tasks:
  predeploy:
    deps:
      - demo-targets:deploy:bodgeit
    cmds:
      - |
        # create a nuclei template configmap from inline definition
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: custom-test-nuclei-templates
          namespace: integration-tests
        data:
          tomcat-detect.yaml: |
            # From: https://github.com/projectdiscovery/nuclei-templates/blob/6d6b72188de42f9318ea766839a74a3771d8bda1/http/technologies/apache/tomcat-detect.yaml MIT License
            id: tomcat-detect

            info:
              name: Tomcat Detection
              author: philippedelteil,dhiyaneshDk,AdamCrosser
              severity: info
              description: If an Tomcat instance is deployed on the target URL, when we send a request for a non existent resource we receive a Tomcat error page with version.
              classification:
                cpe: cpe:2.3:a:apache:tomcat:*:*:*:*:*:*:*:*
              metadata:
                max-request: 3
                vendor: apache
                product: tomcat
                shodan-query:
                  - title:"Apache Tomcat"
                  - http.title:"apache tomcat"
                  - http.html:"apache tomcat"
                  - cpe:"cpe:2.3:a:apache:tomcat"
                fofa-query:
                  - body="apache tomcat"
                  - title="apache tomcat"
                google-query: intitle:"apache tomcat"
              tags: tech,tomcat,apache,intrusive

            http:
              - method: GET
                path:
                  - "{{"{{"}}BaseURL{{"}}"}}"
                  - "{{"{{"}}BaseURL{{"}}"}}/{{"{{"}}randstr{{"}}"}}"
                  - "{{"{{"}}BaseURL{{"}}"}}/docs/introduction.html"

                stop-at-first-match: true

                matchers-condition: or
                matchers:
                  - type: dsl
                    dsl:
                      - 'contains(tolower(header), "tomcat")'

                  - type: dsl
                    dsl:
                      - 'contains(tolower(body), "apache tomcat")'
                      - 'contains(tolower(body), "/manager/html")'
                      - 'contains(tolower(body), "/manager/status")'
                    condition: or

                extractors:
                  - type: regex
                    name: version
                    group: 1
                    regex:
                      - '(?i)Apache Tomcat.*\D([1-9]*[0-9]\.[0-9]+\.[0-9]+)'
        EOF
