version: "3"

includes:
  scanner:
    taskfile: ../Taskfile.yaml
    flatten: true
    excludes:
      - predeploy
    vars:
      scannerName: semgrep

tasks:
  predeploy:
    cmds:
      - kubectl -n integration-tests create configmap semgrep-test-file --from-file=integration-tests/testfile.py --dry-run=client -o yaml | kubectl apply -f -
