version: "3"

includes:
  scanner:
    taskfile: ../Taskfile.yaml
    flatten: true
    vars:
      scannerName: nmap

tasks:
  default:
    desc: Build the Docker image for the Nmap scanner
    cmds:
      - docker build -t securecodebox/nmap:${IMG_TAG} .
    silent: true
