version: "3"

includes:
  scanner:
    taskfile: ../Taskfile.yaml
    flatten: true
    excludes:
      - predeploy
    vars:
      scannerName: wpscan

tasks:
  predeploy:
    deps:
      - demo-targets:deploy:old-wordpress
    cmds: []
