# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

version: "3.44.0"

includes:
  scanner:
    taskfile: ../Taskfile.yaml
    flatten: true
    excludes:
      - predeploy
    vars:
      scannerName: ffuf

tasks:
  predeploy:
    deps:
      - demo-targets:deploy:juice-shop
    cmds:
      - kubectl apply -f ./integration-tests/configmap-wordlist.yaml -n integration-tests
