version: "3"

includes:
  scanner:
    taskfile: ../Taskfile.yaml
    flatten: true
    excludes:
      - predeploy
    vars:
      hookName: notification
      additionalHelmInstallArgsForHook: |
        --values=./integrations-tests/notification-hook-helm-values.yaml \

tasks:
  predeploy:
    deps:
      - demo-targets:deploy:http-webhook
