version: "3"

includes:
  scanner:
    taskfile: ../Taskfile.yaml
    flatten: true
    excludes:
      - predeploy
    vars:
      scannerName: sslyze

tasks:
  predeploy:
    deps:
      - demo-targets:deploy:unsafe-https
    cmds: []
